Problem: cob domain is unavailable even after motr ios is started
Seagate/cortx-ha pull request #173
Opened 2020-09-29 16:18 UTC by mssawant

## Problem Statement
<pre>
  <code>
cob domain is unavailable even after motr ios is started
  </code>
</pre>
## Unit testing on RPM done
<pre>
  <code>
  Yes, on hardware system.
  </code>
</pre>
## Problem Description
<pre>
  <code>
After motr-mkfs, motr ioservices are needed to be started to facilitate cob
domain creation which is not created as part of mkfs operation.
But still cob domain is not available even after motr ioservice reported
M0_CONF_HA_PROCESS_STARTED.
  </code>
</pre>
## Solution
<pre>
  <code>
- Wait for sometime (15 secs) before stopping motr ioservices to allow
  some time for cob domain creation.
- Fix typo and invoke cleanup before checking for consul service at mkfs
  start.
  </code>
</pre>
## Unit Test Cases
<pre>
  <code>
Tested on hardware, script completed successfully.
  </code>
</pre>

2020-09-29 16:38 UTC, shashank-parulekar approved these changes

2020-09-29 16:51 UTC, andriytk commented
Looks like the same as #172 just to the main branch.

2020-09-29 16:54 UTC, mssawant commented
@andriytk , yes

2020-10-06 07:06 UTC, ajaysrivas commented
@mssawant, This is already merged to cortx-1.0. Are we waiting for something to get it merged in main ?

2020-10-07 17:26 UTC, shashank-parulekar requested changes

2020-10-07 17:26 UTC, shashank-parulekar commented on conf/script/prov-m0-reset
> +has_m0d_started() {
On line # 108 of this file for the case single-node the shift should not have '2' after it.
Please put this fix in cortx-1.0 too.

2020-10-07 17:42 UTC, andriytk reviewed
I don't think this "technical debt" should go to the main branch. I hope Motr-team could fix it properly by the time the main branch will start to be tested by QAs...

2020-10-09 05:29 UTC, ajaysrivas commented
This is a work around and should not go into main branch. Motr team should fix it.

2020-10-09 05:29 UTC, closed without merging